### PR TITLE
add parea

### PR DESCRIPTION
**Pull request by joschkabraun**
Adding Parea (YC S23) as a tool to experiment with prompts for the GPT-4V API across inputs. Demo video below

https://github.com/roboflow/awesome-openai-vision-api-experiments/assets/47435119/fbdf0863-ae1c-4329-a334-814836317b8d

### CODE REVIEW

**Comment by asim-shrestha** [comment]
Very cool!

**Comment by wangwenqiao666** [comment]
well, nice!

**Comment by joschkabraun** [comment]
@SkalskiP is that relevant for this repo as additional resource along with papers & blog posts?

**Comment by capjamesg** [comment]
Closing since the page is a 404.

**Pull request closed without merging**
